name: blogsite

services:
    db:
      image: mongo:latest
      container_name: mongodb
      ports:
          - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: sourabh
        MONGO_INITDB_ROOT_PASSWORD: sourabh